version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/pool.db
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pooldb
      - POSTGRES_USER=pooladmin
      - POSTGRES_PASSWORD=secretpassword

  bot:
    build: .
    command: python bot.py
    volumes:
      - .:/app
    depends_on:
      - web
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

volumes:
  postgres_data:
